// Generated by CoffeeScript 1.6.3
/* StackLint (c) FakeRainBrigand 2013
  This file uses jQuery, anyorigin.com, and various techniques to extract data from a stackoverflow question
*/


(function() {
  var $, StackQuestion, anyorigin, root, stackquestion;

  if (typeof window === "undefined" || window === null) {
    throw "soparse.coffee doesn't function without a browser environment";
  }

  if (($ = jQuery) == null) {
    throw "jQuery required to access the stackoverflow question";
  }

  root = window;

  anyorigin = "http://anyorigin.com/get?url=";

  stackquestion = "stackoverflow.com/questions";

  StackQuestion = (function() {
    function StackQuestion(questionId) {
      this.id = ko.observable(questionId != null ? questionId : '');
      this.title = ko.observable('Loading Question');
      this.url = ko.observable('');
      this.html = ko.observable('');
      this.tags = ko.observableArray([]);
      this.code = ko.observableArray([]);
      this.text = ko.observableArray([]);
      this.links = ko.observableArray([]);
      this.user = ko.observable('');
      if (questionId != null) {
        this.handleId(questionId);
      }
      this.id.subscribe(this.handleId.bind(this));
    }

    StackQuestion.prototype.handleId = function(questionId) {
      var _this = this;
      return $.getJSON("" + anyorigin + stackquestion + "/" + questionId + "/&callback=?", function(data) {
        _this.el = $(data.contents).find('#content');
        _this.el.remove('script');
        _this.title(_this.parseTitle());
        _this.url(_this.parseUrl());
        _this.tags(_this.parseTags());
        _this.code(_this.parseCode());
        _this.text(_this.parseText());
        _this.links(_this.parseLinks());
        return _this.user(_this.parseUser());
      });
    };

    StackQuestion.prototype.parseTitle = function() {
      return this.el.find('#question-header a').text();
    };

    StackQuestion.prototype.parseUrl = function() {
      return "http://stackoverflow.com" + this.el.find('#question-header a').attr('href');
    };

    StackQuestion.prototype.parseTags = function() {
      var tags;
      tags = [];
      this.el.find('.post-taglist a').each(function() {
        return tags.push(this.innerText);
      });
      return tags;
    };

    StackQuestion.prototype.parseCode = function() {
      var code;
      code = [];
      this.el.find('.postcell pre').each(function() {
        return code.push(this.innerText);
      });
      return code;
    };

    StackQuestion.prototype.parseText = function() {
      var text;
      text = [];
      this.el.find('.postcell .post-text p').each(function() {
        return text.push(this.innerText);
      });
      return text;
    };

    StackQuestion.prototype.parseLinks = function() {
      var links;
      links = [];
      this.el.find('.postcell .post-text a').each(function() {
        return links.push({
          href: this.href,
          text: this.innerText
        });
      });
      return links;
    };

    StackQuestion.prototype.parseUser = function() {
      var a;
      a = this.el.find('.user-details a').get(0);
      return {
        href: "http://stackoverflow.com" + a.pathname,
        name: a.innerText
      };
    };

    return StackQuestion;

  })();

  root.StackQuestion = StackQuestion;

}).call(this);

/*
//@ sourceMappingURL=soparse.map
*/
