// Generated by CoffeeScript 1.6.3
(function() {
  var __slice = [].slice;

  ko.observable.fn.contains = function() {
    var data, value, values, _i, _len;
    values = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    data = this();
    for (_i = 0, _len = values.length; _i < _len; _i++) {
      value = values[_i];
      if (data.indexOf(value !== -1)) {
        return true;
      }
    }
    return false;
  };

}).call(this);

/*
//@ sourceMappingURL=stacklint.ko.map
*/
